### ISSUE TITLE
test_inputs variable not defined in Corona.ipynb

### ISSUE THREAD

**Issue by dmandreev** [LuanAdemi/LSTM-TSP#1]
Could you please fix it, or give a hint.  I'm trying to reproduce your results, but with no success.

NameError                                 Traceback (most recent call last)
<ipython-input-19-a7a32113072e> in <module>()
      5 
      6 for i in range(fut_pred):
----> 7     seq = torch.FloatTensor(test_inputs[-train_window:])
      8     with torch.no_grad():
      9         model.hidden = (torch.zeros(1, 1, model.hidden_layer_size),

NameError: name **'test_inputs'** is not defined

**Comment by LuanAdemi** [comment]
Sure! Sorry, I must have somehow deleted the definition of the variable 'test_inputs'. It's fixed now!
